project_id = "vlavfpvrxnmoutybczfy"

[functions.geo-group-assign]
verify_jwt = false

[functions.apply-to-internship]
verify_jwt = false

[functions.ai-recommendations]
verify_jwt = false

[functions.recommendation-feedback]
verify_jwt = false

[functions.student-reputation]
verify_jwt = false

[functions.skill-tests]
verify_jwt = false

[functions.campus-status]
verify_jwt = false
